// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer DIRECT_URL (port 5432) so `prisma migrate` uses a direct
    // connection — the pooler (6543) blocks advisory locks. Runtime client
    // (lib/db.ts) still uses DATABASE_URL (pooler) for serverless.
    url:
      process.env["DIRECT_URL"] ||
      process.env["DATABASE_URL"] ||
      "postgresql://postgres:postgres@localhost:5432/videology",
  },
});
